In [2]:
import pandas as pd

## Transform File Json Person-GeneralContact

In [3]:
import json
import pandas as pd
from typing import List, Dict, Any
json_path_1 = "Person-GeneralContact.json"

# ────────────────────────────────────────────────────────────────────────────────
# Helper lambda: lấy phần tử đầu tiên hoặc trả "" nếu không tồn tại
first_or_empty = lambda lst: (lst or [""])[0] if isinstance(lst, list) else ""

def parse_person_data(json_path: str) -> pd.DataFrame:
    """
    Đọc file JSON và trả về DataFrame phẳng.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records: List[Dict[str, Any]] = []

    for item in data:
        person        = first_or_empty(item.get("PersonInfo"))
        contact       = first_or_empty(person.get("PersonContact", []))
        address       = first_or_empty(contact.get("PersonAddress", []))
        address_detail = first_or_empty(address.get("PersonAddressDetail", []))

        records.append({
            "BusinessEntityID"   : item.get("BusinessEntityID"),
            "PersonType"         : item.get("PersonType"),
            "ModifiedDate"       : item.get("ModifiedDate"),
            "FirstName"          : person.get("FirstName", ""),
            "MiddleName"         : person.get("MiddleName", ""),
            "LastName"           : person.get("LastName", ""),
            "PersonAddressDetail": address_detail or ""   # rỗng = ""
        })

    return pd.DataFrame(records)

In [4]:
df_2 = parse_person_data("Person-GeneralContact.json")

In [5]:
df_2

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,PersonAddressDetail
0,2091,GC,2017-12-13T13:22:10.163,David,J,Ortiz,
1,2092,GC,2017-12-13T13:22:10.193,Qiang,,Wang,
2,2093,GC,2017-12-13T13:22:10.240,Andy,,Teal,
3,2094,GC,2017-12-13T13:22:10.270,Jeff,,Pike,
4,2095,GC,2017-12-13T13:22:10.320,Gregory,J,Erickson,
...,...,...,...,...,...,...,...
284,2375,GC,2017-12-13T13:22:21.477,Michael,,Allen,
285,2376,GC,2017-12-13T13:22:21.507,Claire,,O'Donnell,
286,2377,GC,2017-12-13T13:22:21.553,Susan,,Metters,
287,2378,GC,2017-12-13T13:22:21.587,Sue,,Brown,
288,2379,GC,2017-12-13T13:22:21.633,Ben,,Hurt,

In [6]:
df_filtered = df_2[df_2["PersonAddressDetail"] == "address_detail"]

In [7]:
df_filtered

Empty DataFrame
Columns: [BusinessEntityID, PersonType, ModifiedDate, FirstName, MiddleName, LastName, PersonAddressDetail]
Index: []

In [8]:
df_2['ModifiedDate'] = pd.to_datetime(df_2['ModifiedDate'])
df_2["ModifiedDate"] = df_2["ModifiedDate"].dt.strftime("%m-%d-%Y")

In [9]:
df_2

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,PersonAddressDetail
0,2091,GC,12-13-2017,David,J,Ortiz,
1,2092,GC,12-13-2017,Qiang,,Wang,
2,2093,GC,12-13-2017,Andy,,Teal,
3,2094,GC,12-13-2017,Jeff,,Pike,
4,2095,GC,12-13-2017,Gregory,J,Erickson,
...,...,...,...,...,...,...,...
284,2375,GC,12-13-2017,Michael,,Allen,
285,2376,GC,12-13-2017,Claire,,O'Donnell,
286,2377,GC,12-13-2017,Susan,,Metters,
287,2378,GC,12-13-2017,Sue,,Brown,
288,2379,GC,12-13-2017,Ben,,Hurt,

In [10]:
df_2.dtypes
df_2['ModifiedDate'] = pd.to_datetime(df_2['ModifiedDate'])

In [11]:
df_2.dtypes

BusinessEntityID                int64
PersonType                     object
ModifiedDate           datetime64[ns]
FirstName                      object
MiddleName                     object
LastName                       object
PersonAddressDetail            object
dtype: object

In [12]:
check_middlename = df_2['MiddleName'].unique()
for value in check_middlename:
    print(value)

J

E
Ann
William
F
T
Scott
E.
Barreiro Gambaro
H

## Transform File Json Person--IndividualCustomer

In [13]:
# Helper: lấy phần tử đầu hoặc rỗng
first_or_empty = lambda lst: (lst or [{}])[0] if isinstance(lst, list) else {}

def parse_extended_person_data(json_path: str) -> pd.DataFrame:
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records = []

    for item in data:
        person = first_or_empty(item.get("PersonInfo"))
        contact = first_or_empty(person.get("PersonContact"))
        address = first_or_empty(contact.get("PersonAddress"))
        address_detail = first_or_empty(address.get("PersonAddressDetail"))

        record = {
            "BusinessEntityID": item.get("BusinessEntityID"),
            "PersonType": item.get("PersonType"),
            "ModifiedDate": item.get("ModifiedDate"),
            "FirstName": person.get("FirstName", ""),
            "MiddleName": person.get("MiddleName", ""),
            "LastName": person.get("LastName", ""),
            "AddressLine1": contact.get("AddressLine1", ""),
            "City": contact.get("City", ""),
            "PostalCode": contact.get("PostalCode", ""),
            "AddressName": address.get("AddressName", ""),
            "CountryRegionCode": address_detail.get("CountryRegionCode", ""),
            "StateProvinceCode": address_detail.get("StateProvinceCode", ""),
            "StateProvinceName": address_detail.get("StateProvinceName", "")
        }

        records.append(record)

    return pd.DataFrame(records)

In [14]:
df_3 = parse_extended_person_data("Person-IndividualCustomer.Json")
df_3

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,AddressLine1,City,PostalCode,AddressName,CountryRegionCode,StateProvinceCode,StateProvinceName
0,1699,IN,2017-12-13T13:21:47.740,David,R.,Robinett,Pappelallee 6667,Solingen,42651,Home,DE,NW,Nordrhein-Westfalen
1,1700,IN,2017-12-13T13:21:47.803,Rebecca,A.,Robinson,1861 Chinquapin Ct,Seaford,3198,Home,AU,VIC,Victoria
2,1701,IN,2017-12-13T13:21:47.850,Dorothy,B.,Robinson,4693 Mills Dr.,Geelong,3220,Home,AU,VIC,Victoria
3,1702,IN,2017-12-13T13:21:47.913,Carol Ann,F.,Rockne,1312 Skycrest Drive,Lancaster,LA1 1LN,Home,GB,ENG,England
4,1703,IN,2017-12-13T13:21:47.960,Scott,M.,Rodgers,9860 Brookview Drive,East Brisbane,4169,Home,AU,QLD,Queensland
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18479,20773,IN,2017-12-13T13:47:22.187,Crystal,,Guo,988 Mt. Everest Court,W. York,BD1 4SJ,Home,GB,ENG,England
18480,20774,IN,2017-12-13T13:47:22.250,Isabella,F,Richardson,7413 Alpine Drive,Torrance,90505,Home,US,CA,California
18481,20775,IN,2017-12-13T13:47:22.310,Crystal,S,He,4764 East Avenue,Bremerton,98312,Home,US,WA,Washington
18482,20776,IN,2017-12-13T13:47:22.390,Crystal,,Zheng,"34334, rue Jean Mermoz",Versailles,78000,Home,FR,78,Yveline
18483,20777,IN,2017-12-13T13:47:22.467,Crystal,,Hu,6022 La Salle Ct.,Darlinghurst,2010,Home,AU,NSW,New South Wales

## Transform File Json Person-Non-salesEmployee.Json

In [15]:
# Hàm phụ trợ: lấy phần tử đầu tiên nếu là list, hoặc {} nếu rỗng
first_or_empty = lambda lst: (lst or [{}])[0] if isinstance(lst, list) else {}

def parse_person_json(json_path: str) -> pd.DataFrame:
    """
    Phân tích file JSON có cấu trúc nested của Person → chuyển thành DataFrame phẳng.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records = []

    for item in data:
        person = first_or_empty(item.get("PersonInfo"))
        contact = first_or_empty(person.get("PersonContact"))
        address = first_or_empty(contact.get("PersonAddress"))
        address_detail = first_or_empty(address.get("PersonAddressDetail"))

        record = {
            "BusinessEntityID"  : item.get("BusinessEntityID"),
            "PersonType"        : item.get("PersonType"),
            "ModifiedDate"      : item.get("ModifiedDate"),
            "FirstName"         : person.get("FirstName", ""),
            "MiddleName"        : person.get("MiddleName", ""),
            "LastName"          : person.get("LastName", ""),
            "AddressLine1"      : contact.get("AddressLine1", ""),
            "City"              : contact.get("City", ""),
            "PostalCode"        : contact.get("PostalCode", ""),
            "AddressName"       : address.get("AddressName", ""),
            "CountryRegionCode" : address_detail.get("CountryRegionCode", ""),
            "StateProvinceCode" : address_detail.get("StateProvinceCode", ""),
            "StateProvinceName" : address_detail.get("StateProvinceName", "")
        }

        records.append(record)

    return pd.DataFrame(records)

In [16]:
df_4 = parse_extended_person_data("Person-Non-salesEmployee.Json")
df_4

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,AddressLine1,City,PostalCode,AddressName,CountryRegionCode,StateProvinceCode,StateProvinceName
0,1,EM,2017-12-13T13:20:24.150,Ken,J,Sánchez,4350 Minute Dr.,Newport Hills,98006,Home,US,WA,Washington
1,2,EM,2017-12-13T13:20:24.430,Terri,Lee,Duffy,7559 Worth Ct.,Renton,98055,Home,US,WA,Washington
2,3,EM,2017-12-13T13:20:24.540,Roberto,,Tamburello,2137 Birchwood Dr,Redmond,98052,Home,US,WA,Washington
3,4,EM,2017-12-13T13:20:24.570,Rob,,Walters,5678 Lakeview Blvd.,Minneapolis,55402,Home,US,MN,Minnesota
4,5,EM,2017-12-13T13:20:24.633,Gail,A,Erickson,9435 Breck Court,Bellevue,98004,Home,US,WA,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,269,EM,2017-12-13T13:20:36.837,Dan,K,Bacon,1921 Ranch Road,Issaquah,98027,Home,US,WA,Washington
269,270,EM,2017-12-13T13:20:36.883,François,P,Ajenstat,1144 Paradise Ct.,Issaquah,98027,Home,US,WA,Washington
270,271,EM,2017-12-13T13:20:36.913,Dan,B,Wilson,5863 Sierra,Bellevue,98004,Home,US,WA,Washington
271,272,EM,2017-12-13T13:20:36.960,Janaina,Barreiro Gambaro,Bueno,5979 El Pueblo,Issaquah,98027,Home,US,WA,Washington
272,273,EM,2017-12-13T13:20:37.010,Brian,S,Welcker,7772 Golden Meadow,Issaquah,98027,Home,US,WA,Washington

In [17]:
df_4['ModifiedDate'] = pd.to_datetime(df_4['ModifiedDate'])
df_4["ModifiedDate"] = df_4["ModifiedDate"].dt.strftime("%m-%d-%Y")
df_4['ModifiedDate'] = pd.to_datetime(df_4['ModifiedDate'])
df_4.dtypes

BusinessEntityID              int64
PersonType                   object
ModifiedDate         datetime64[ns]
FirstName                    object
MiddleName                   object
LastName                     object
AddressLine1                 object
City                         object
PostalCode                   object
AddressName                  object
CountryRegionCode            object
StateProvinceCode            object
StateProvinceName            object
dtype: object

## Transform File Json Person-SalesPerson.Json

In [18]:
# Hàm phụ trợ: lấy phần tử đầu tiên nếu là list, hoặc {} nếu rỗng
first_or_empty = lambda lst: (lst or [{}])[0] if isinstance(lst, list) else {}

def parse_person_json(json_path: str) -> pd.DataFrame:
    """
    Phân tích file JSON có cấu trúc nested của Person → chuyển thành DataFrame phẳng.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records = []

    for item in data:
        person = first_or_empty(item.get("PersonInfo"))
        contact = first_or_empty(person.get("PersonContact"))
        address = first_or_empty(contact.get("PersonAddress"))
        address_detail = first_or_empty(address.get("PersonAddressDetail"))

        record = {
            "BusinessEntityID"  : item.get("BusinessEntityID"),
            "PersonType"        : item.get("PersonType"),
            "ModifiedDate"      : item.get("ModifiedDate"),
            "FirstName"         : person.get("FirstName", ""),
            "MiddleName"        : person.get("MiddleName", ""),
            "LastName"          : person.get("LastName", ""),
            "AddressLine1"      : contact.get("AddressLine1", ""),
            "City"              : contact.get("City", ""),
            "PostalCode"        : contact.get("PostalCode", ""),
            "AddressName"       : address.get("AddressName", ""),
            "CountryRegionCode" : address_detail.get("CountryRegionCode", ""),
            "StateProvinceCode" : address_detail.get("StateProvinceCode", ""),
            "StateProvinceName" : address_detail.get("StateProvinceName", "")
        }

        records.append(record)

    return pd.DataFrame(records)

In [19]:
df_5 = parse_extended_person_data("Person-SalesPerson.Json")
df_5.head(5)

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,AddressLine1,City,PostalCode,AddressName,CountryRegionCode,StateProvinceCode,StateProvinceName
0,274,SP,2017-12-13T13:20:37.053,Stephen,Y,Jiang,2427 Notre Dame Ave.,Redmond,98052,Home,US,WA,Washington
1,275,SP,2017-12-13T13:20:37.117,Michael,G,Blythe,8154 Via Mexico,Detroit,48226,Home,US,MI,Michigan
2,276,SP,2017-12-13T13:20:37.197,Linda,C,Mitchell,2487 Riverside Drive,Nevada,84407,Home,US,UT,Utah
3,277,SP,2017-12-13T13:20:37.587,Jillian,,Carson,80 Sunview Terrace,Duluth,55802,Home,US,MN,Minnesota
4,278,SP,2017-12-13T13:20:37.727,Garrett,R,Vargas,10203 Acorn Avenue,Calgary,T2P 2G8,Home,CA,AB,Alberta

In [20]:
df_5['ModifiedDate'] = pd.to_datetime(df_5['ModifiedDate'])
df_5["ModifiedDate"] = df_4["ModifiedDate"].dt.strftime("%m-%d-%Y")
df_5['ModifiedDate'] = pd.to_datetime(df_5['ModifiedDate'])
df_5.dtypes

BusinessEntityID              int64
PersonType                   object
ModifiedDate         datetime64[ns]
FirstName                    object
MiddleName                   object
LastName                     object
AddressLine1                 object
City                         object
PostalCode                   object
AddressName                  object
CountryRegionCode            object
StateProvinceCode            object
StateProvinceName            object
dtype: object

## Transform File Json Person-StoreContact.Json

In [21]:
# Hàm phụ: lấy phần tử đầu tiên nếu là list, hoặc dict rỗng nếu không
first_or_empty = lambda lst: (lst or [{}])[0] if isinstance(lst, list) else {}

def parse_person_json(json_path: str) -> pd.DataFrame:
    """
    Phân tích file JSON có cấu trúc nested của Person → chuyển thành DataFrame phẳng.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records = []

    for item in data:
        person = first_or_empty(item.get("PersonInfo"))
        contact = first_or_empty(person.get("PersonContact"))
        address = first_or_empty(contact.get("PersonAddress"))
        address_detail = first_or_empty(address.get("PersonAddressDetail"))

        record = {
            "BusinessEntityID"  : item.get("BusinessEntityID"),
            "PersonType"        : item.get("PersonType"),
            "ModifiedDate"      : item.get("ModifiedDate"),
            "FirstName"         : person.get("FirstName", ""),
            "MiddleName"        : person.get("MiddleName", ""),
            "LastName"          : person.get("LastName", ""),
            "AddressLine1"      : contact.get("AddressLine1", ""),
            "City"              : contact.get("City", ""),
            "PostalCode"        : contact.get("PostalCode", ""),
            "AddressName"       : address.get("AddressName", ""),
            "CountryRegionCode" : address_detail.get("CountryRegionCode", ""),
            "StateProvinceCode" : address_detail.get("StateProvinceCode", ""),
            "StateProvinceName" : address_detail.get("StateProvinceName", "")
        }

        records.append(record)
    return pd.DataFrame(records)

In [22]:
df_6 = parse_extended_person_data("Person-StoreContact.Json")
df_6.head(5)

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,AddressLine1,City,PostalCode,AddressName,CountryRegionCode,StateProvinceCode,StateProvinceName
0,291,SC,2017-12-13T13:21:02.150,Gustavo,,Achong,,,,,,,
1,293,SC,2017-12-13T13:21:02.273,Catherine,R.,Abel,,,,,,,
2,295,SC,2017-12-13T13:21:02.337,Kim,,Abercrombie,,,,,,,
3,297,SC,2017-12-13T13:21:02.400,Humberto,,Acevedo,,,,,,,
4,299,SC,2017-12-13T13:21:02.460,Pilar,,Ackerman,,,,,,,

In [23]:
check_middlename = df_6['MiddleName'].unique()
for value in check_middlename:
    print(value)

R.
B.
J.
L.
N.
T.
E.
A.
F.
P.
H
M.
K.
M
Greg
H.
Y.
S.
B
R
Beth
D.
Yuan
T
O
Francesca
Z.
I.
C.
Brian
Rudra
Shuo

## Transform File Json Person-VendorContract.Json

In [24]:
# Hàm phụ: lấy phần tử đầu tiên nếu là list, hoặc dict rỗng nếu không
first_or_empty = lambda lst: (lst or [{}])[0] if isinstance(lst, list) else {}

def parse_person_json_7(json_path: str) -> pd.DataFrame:
    """
    Phân tích file JSON có cấu trúc nested của Person → chuyển thành DataFrame phẳng.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        data: List[Dict[str, Any]] = json.load(f)

    records = []

    for item in data:
        person = first_or_empty(item.get("PersonInfo"))
        contact = first_or_empty(person.get("PersonContact"))
        address = first_or_empty(contact.get("PersonAddress"))
        address_detail = first_or_empty(address.get("PersonAddressDetail"))

        record = {
            "BusinessEntityID"  : item.get("BusinessEntityID"),
            "PersonType"        : item.get("PersonType"),
            "ModifiedDate"      : item.get("ModifiedDate"),
            "FirstName"         : person.get("FirstName", ""),
            "MiddleName"        : person.get("MiddleName", ""),
            "LastName"          : person.get("LastName", ""),
            "PersonAddressDetail"  : address_detail.get("PersonAddressDetail", ""),
        }

        records.append(record)
    return pd.DataFrame(records)

In [25]:
df_7 = parse_person_json_7("Person-VendorContact.Json")
df_7.head(5)

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,PersonAddressDetail
0,1491,VC,2017-12-13T13:21:41.257,Paula,B.,Moberly,
1,1493,VC,2017-12-13T13:21:41.350,Suchitra,,Mohan,
2,1495,VC,2017-12-13T13:21:41.430,Jonathan,,Moeller,
3,1497,VC,2017-12-13T13:21:41.490,William,J.,Monroe,
4,1499,VC,2017-12-13T13:21:41.553,Alan,L.,Monitor,

In [26]:
address_cols = [
    "PersonAddressDetail"
]

# In số lượng giá trị unique mỗi cột
for col in address_cols:
    unique_count = df_7[col].nunique(dropna=True)
    print(f"{col}: {unique_count} unique value(s)")

PersonAddressDetail: 1 unique value(s)

In [27]:
df_2.to_csv("df_2_export.csv", index=False, encoding="utf-8")

In [28]:
df_3.to_csv("df_3_export.csv", index=False, encoding="utf-8")
df_4.to_csv("df_4_export.csv", index=False, encoding="utf-8")
df_5.to_csv("df_5_export.csv", index=False, encoding="utf-8")
df_6.to_csv("df_6_export.csv", index=False, encoding="utf-8")
df_7.to_csv("df_7_export.csv", index=False, encoding="utf-8")

In [29]:
pd.read_csv('df_2_export.csv')

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,PersonAddressDetail
0,2091,GC,2017-12-13,David,J,Ortiz,NaN
1,2092,GC,2017-12-13,Qiang,NaN,Wang,NaN
2,2093,GC,2017-12-13,Andy,NaN,Teal,NaN
3,2094,GC,2017-12-13,Jeff,NaN,Pike,NaN
4,2095,GC,2017-12-13,Gregory,J,Erickson,NaN
...,...,...,...,...,...,...,...
284,2375,GC,2017-12-13,Michael,NaN,Allen,NaN
285,2376,GC,2017-12-13,Claire,NaN,O'Donnell,NaN
286,2377,GC,2017-12-13,Susan,NaN,Metters,NaN
287,2378,GC,2017-12-13,Sue,NaN,Brown,NaN
288,2379,GC,2017-12-13,Ben,NaN,Hurt,NaN

## Import file to Snowflake

In [30]:
df_2.head(5)

,BusinessEntityID,PersonType,ModifiedDate,FirstName,MiddleName,LastName,PersonAddressDetail
0,2091,GC,2017-12-13,David,J,Ortiz,
1,2092,GC,2017-12-13,Qiang,,Wang,
2,2093,GC,2017-12-13,Andy,,Teal,
3,2094,GC,2017-12-13,Jeff,,Pike,
4,2095,GC,2017-12-13,Gregory,J,Erickson,

## Import file csv into Snowflake through PUT - COPY method

In [32]:
from pathlib import Path
import pyodbc
import pandas as pd
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas
import os

# === 2. KẾT NỐI SNOWFLAKE ===
sf_conn = snowflake.connector.connect(
    user='Huynhhieu1710',
    password='17102003Huynhconghieu@',
    account='ij46654.southeast-asia.azure',
    warehouse='DATA_WAREHOUSE_DEMO',
    database='PERSON_TRANS_COUNTRY_DTB',
    schema='PUBLIC',
    role='SYSADMIN'
)
cursor = sf_conn.cursor()

# ==== 3. TẠO HÀM TẠO BẢNG TỰ ĐỘNG ====
def generate_create_table_sql(df, table_name):
    dtype_mapping = {
        'object': 'VARCHAR(500)',
        'int64': 'INTEGER',
        'float64': 'FLOAT',
        'bool': 'BOOLEAN',
        'datetime64[ns]': 'TIMESTAMP'
    }
    columns = []
    for col, dtype in df.dtypes.items():
        sf_type = dtype_mapping.get(str(dtype), 'VARCHAR(500)')
        columns.append(f'"{col}" {sf_type}')
    create_sql = f"CREATE OR REPLACE TABLE {table_name} (\n  {',\n  '.join(columns)}\n)"
    return create_sql

# ==== 4. TẠO BẢNG TỰ ĐỘNG ====
table_name = "Person_Vendor_Contact"
create_sql = generate_create_table_sql(df_7, table_name)
cursor.execute(create_sql)

# ==== 5. EXPORT CSV ====
csv_file = "df_Person_Contact.csv"
df_7.to_csv(csv_file, index=False)

# ==== 6. PUT FILE LÊN STAGE ====
csv_path = Path(csv_file).resolve()
put_command = f"PUT 'file://{csv_path.as_posix()}' @%{table_name} OVERWRITE = TRUE"
cursor.execute(put_command)

# ==== 7. COPY DỮ LIỆU VÀO BẢNG ====
copy_command = f"""
    COPY INTO {table_name}
    FROM @%{table_name}
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
"""
cursor.execute(copy_command)


os.remove(csv_file)
# cursor.close()
# sf_conn.close()

print(" Đã import dữ liệu từ SQL Server vào Snowflake thành công!")

 Đã import dữ liệu từ SQL Server vào Snowflake thành công!